### ISSUE TITLE
32bit DMXSerial for Teensy 3.2

### ISSUE THREAD

**Issue by henryflorence** [mathertel/DMXSerial#8] opened 2016-12-23 21:27 UTC
I am interested in using the dmx out, in and rdm capabilities of your libraries, as these currently seem to be the most complete. I am currently developing on arduino, but looking to port to teensy to utilise the increased resources.

Do you have any intention of porting to this platform? Or could you offer some guidelines as to how the task could be achieved. I noticed what looks like some of the DMXSerial code in DMXSimple which currently supports Teensy, but only for output.

**Comment by s-light** [comment] 2018-11-26 19:09
could be a duplicate of #1

**Comment by mathertel** [comment] 2020-02-26 20:37
With version 1.5 there is a processor specific layer that allows supporting multiple processor architectures. Please have a look if you like to try implementing Teensy support.

**Comment by mathertel** [comment] 2021-03-08 15:31
For Teensy there is another project that may fit: https://github.com/ssilverman/TeensyDMX

**Closed by mathertel** 2021-03-08 15:31 UTC
Labels: enhancement
